# Generated by Django 4.1.4 on 2022-12-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='isActive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
